POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3Mjc1MDg0NzksInVzZXJJZCI6MH0.tjr7jjwUBEVdOpKDe0moIMvfBgMIZwYfHfDq0WsjlT8

{
    "name": "test event-1",
    "description": "A test event 1",
    "location": "A test location",
    "datatime": "2024-02-02T15:30:00.000Z"
}