POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3MjgzNDQzMTMsInVzZXJJZCI6MH0.Gvr-KIro-1G48azxatgrKioGsRRgL7Ewdm17jKi6IfE

{
    "name": "test event-1",
    "description": "A test event 1",
    "location": "A test location",
    "datatime": "2024-02-02T15:30:00.000Z"
}