POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlc3QuY29tIiwiZXhwIjoxNzI4MzQ4OTg2LCJ1c2VySWQiOjJ9.-EQeIjVuWylMpk5HoChh7IpihHyaleqaJJlqaJ01mA0

{
    "name": "test event-2",
    "description": "A test event 2",
    "location": "A test location 2",
    "datatime": "2024-02-02T15:30:00.000Z"
}