PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "name": "Updated test event",
    "description": "test updated",
    "location":"test location - van",
    "datatime": "2024-01-02T15:30:00Z"
}